# Generated by Django 4.1.6 on 2023-02-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=250)),
                ('massage', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Ship_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=250)),
                ('senders_email', models.CharField(max_length=250)),
                ('senders_phone_no', models.IntegerField(max_length=250)),
                ('senders_address', models.CharField(max_length=250)),
                ('receivers_name', models.CharField(max_length=250)),
                ('receivers_email', models.CharField(max_length=250)),
                ('receivers_phone_no', models.IntegerField(max_length=250)),
                ('receivers_address', models.CharField(max_length=250)),
                ('receivers_Zip_code', models.CharField(max_length=250)),
                ('Estimated_parcels_weight', models.CharField(max_length=250)),
                ('massage', models.TextField(blank=True, null=True)),
                ('tracking_id', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
