# Generated by Django 4.1.6 on 2023-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_booking',
            name='receivers_phone_no',
        ),
        migrations.RemoveField(
            model_name='ship_booking',
            name='senders_phone_no',
        ),
        migrations.AddField(
            model_name='ship_booking',
            name='phone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
