# Generated by Django 4.1.6 on 2023-02-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0002_remove_ship_booking_receivers_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_booking',
            name='receivers_phone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
