# Generated by Django 4.1.6 on 2023-02-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0003_ship_booking_receivers_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_booking',
            name='tracking_id',
        ),
    ]
