# Generated by Django 4.1.6 on 2023-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0004_remove_ship_booking_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_booking',
            name='tracking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
