# Generated by Django 4.1.6 on 2023-02-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0007_alter_ship_booking_senders_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship_booking',
            old_name='phone_no',
            new_name='senders_phone_no',
        ),
    ]
