# Generated by Django 4.1.6 on 2023-02-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0008_rename_phone_no_ship_booking_senders_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_booking',
            name='senders_phone_no',
        ),
    ]
