# Generated by Django 4.1.6 on 2023-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0009_remove_ship_booking_senders_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_booking',
            name='senders_phone_no',
            field=models.CharField(max_length=250, null='null'),
            preserve_default='null',
        ),
    ]
