# Generated by Django 4.1.6 on 2023-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0010_ship_booking_senders_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_booking',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
