# Generated by Django 4.1.6 on 2023-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0011_ship_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_Payment_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=250)),
                ('btc_coin', models.CharField(max_length=250)),
                ('ETH_coin', models.CharField(max_length=250)),
                ('BNB_coin', models.CharField(max_length=250)),
                ('USDT_coin', models.CharField(max_length=250)),
            ],
        ),
    ]
