# Generated by Django 4.1.6 on 2023-03-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0013_delivery_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_destination',
            old_name='status',
            new_name='delivery_status',
        ),
    ]
