# Generated by Django 4.1.6 on 2023-03-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0017_alter_delivery_destination_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_destination',
            name='user',
        ),
    ]
