# Generated by Django 5.0.1 on 2024-03-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0018_remove_delivery_destination_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(max_length=250)),
                ('applicants_email', models.CharField(max_length=250)),
                ('applicants_phone_no', models.CharField(max_length=250, null='null')),
                ('applicants_address', models.CharField(max_length=250)),
                ('applicants_state', models.CharField(max_length=250)),
                ('applicants_city', models.CharField(max_length=250)),
                ('applicants_zip', models.CharField(max_length=250)),
                ('upload_id', models.ImageField(blank=True, default='', null=True, upload_to='images')),
            ],
            options={
                'ordering': ['-applicants_zip'],
            },
        ),
    ]
