# Generated by Django 5.0.1 on 2024-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsApp', '0019_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='applicants_ssn',
            field=models.CharField(default='', max_length=250),
        ),
    ]
